name: Arduino Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Install Arduino boards and libraries
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr
          arduino-cli lib install "ArduinoUnit"

      - name: Compile and run tests
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./path/to/your/sketch

      - name: Check for successful build
        run: |
          echo "Build and test compilation was successful!"

